In [1]:
%pip install nptyping beartype --upgrade --force

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     ------------------------------- ------ 51.2/61.0 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---- ----------------------------------- 112.6/917.8 kB 3.3 MB/s eta 0:00:01
   ---- ----------------------------------- 112.6/917.8 kB 3.3 MB/s eta 0:00:01
   ---------- ----------------------------- 235.5/917.8 kB 2.1 MB/s eta 0:00:01
   ---------- ----------------------------- 235.5/917.8 kB 2.1 MB/s eta 0:00:01
   --------------- ------------------------ 358.4/917.8 kB 1.7 MB/s eta 0:00:01
   ----------------- ---------------------- 399.4/917.8 kB 1.7 MB/s eta 0:00:01
   ------------------------ --------------- 553.0/917.8 kB 1.7 MB/s eta 0:00:01
   ------------------------ --------------- 553.0/917.8 kB 1.7 M

# Scalar value

In [76]:
import numpy as np

a : np.ndarray = np.array(11)
display(a)
display(a.shape)
display(a.dtype)
display(type(a))
display(a.ndim)
display(a.size)
display(a.itemsize)

array(11)

()

dtype('int32')

numpy.ndarray

0

1

4

# Vector Value

In [5]:
b : np.ndarray = np.array([1,2,3,4])

display(b)

array([1, 2, 3, 4])

# Numpy with NDArray typing support

In [11]:
from nptyping import NDArray,Shape,UInt64
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,11)
print(data)
print(data + 5)         

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [12]:
%%time

from nptyping import NDArray,Shape,UInt64
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,11)
print(data)
print(data + 5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
CPU times: total: 0 ns
Wall time: 3.99 ms


In [14]:
%%time
from nptyping import NDArray,Shape,UInt64

data : list[int] = list(range(1,1000))
[i+5 for i in data]

CPU times: total: 0 ns
Wall time: 0 ns


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [15]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000 # normal python list
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [19]:
# the above method can be deone easily by NDArray

ndata : NDArray[Shape["20"],Any] = np.arange(1,21)
print(ndata)
ndata[5:11] = 1000
print(ndata)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d functions

In [20]:
from nptyping import Bool

state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])

copetitor : NDArray[Shape["10"],Bool] = np.array([True,False,False,True])

state_bank[copetitor]


array([ 1, 10])

In [21]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank%2==0

array([False, False,  True,  True])

In [23]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank[state_bank%2==0]

array([ 8, 10])

In [30]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,22,3)
mzn_bank : NDArray[Shape["100"],Any] = np.random.randint(1,22,20)
display(state_bank)
display(ubl_bank)
display(mzn_bank)


array([ 1,  7,  8, 10])

array([18,  8,  7])

array([ 7, 13,  6, 18, 18, 13, 17, 10, 20, 15,  8, 13,  9, 11, 19,  8,  7,
       19,  5,  6])

```
in1d is a function in the NumPy library in Python. It is used to test whether each element of a given array is present in another array. The function returns a boolean array that has the same length as the first array, where each value is True if the element is in the second array and False otherwise.
```

In [36]:
np.in1d(state_bank,ubl_bank) # only 7 and 8 were found in match/intersection

array([False,  True,  True, False])

In [34]:
state_bank[np.in1d(state_bank,ubl_bank)]

array([7, 8])

In [37]:
np.intersect1d(state_bank,ubl_bank) # will print the intersection elements

array([7, 8])

In [41]:
group1 : NDArray[Shape["10"],Any] = np.array([1,3,4,5,7])
group2 : NDArray[Shape["10"],Any] = np.array([6,3,2,5,100])

display(group1,group2)
np.where(group1>group2, group1,group2)

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

# Create Numpy arrays

In [47]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])

b : NDArray[Shape["Size , Size"],Any] = np.array([[2,6],
                                                [7,8]])

c : NDArray[Shape["Size , Size"],Any] = np.array([["A"],
                                                  ["B"]])

print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[2 6]
 [7 8]]
[['A']
 ['B']]


In [51]:
x : NDArray[Shape["* , *"],Any] = np.array([[1,2,3],[3,4,5]])
y : NDArray[Shape["* , *"],Any] = np.array([[4,3],[1,1]])
n : NDArray[Shape["* , *"],Any] = np.array([["s"],["d"]])

print(x)
print(y)
print(n)

[[1 2 3]
 [3 4 5]]
[[4 3]
 [1 1]]
[['s']
 ['d']]


# Create any dimension array

In [52]:
a : NDArray[Shape["Size , Size"],Any] = np.arange(3*3).reshape(3,3)
display(a)
b : NDArray[Shape["Size , Size"],Any] = np.arange(5*3).reshape(5,3)
display(b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [59]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)  # 3 rows X 3 cols x 2 sets
display(a)
print("=======")

b : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(b)



array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [57]:
v : NDArray[Shape["Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
display(v) 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [61]:
t : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
display(t)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [62]:
t[::2,::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [63]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [65]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [68]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [70]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[[0,-1],::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [74]:
num_data : NDArray[Shape["20"],Any] = np.arange(1,21)
print(num_data)
print(num_data.argmax())
print(num_data.argmin())
print(num_data.max())
print(num_data.min())
print(num_data.mean())
print(num_data.std())
print(num_data.sum())
print(num_data.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
19
0
20
1
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


In [73]:
[i for i in dir(num_data) if "__" not in i ]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']